create table if not exists public.area_submission_criterion_scores (
  score_id bigint generated by default as identity not null,
  submission_id bigint not null,
  application_id bigint not null,
  area_id bigint not null,
  part_id character varying(128) null,
  criterion_key character varying(128) not null,
  criterion_label character varying(255) not null,
  criterion_title text null,
  criterion_max_points numeric(10, 2) not null default 0.00,
  score numeric(10, 2) not null default 0.00,
  notes text null,
  reviewed_by integer null,
  reviewed_at timestamp with time zone null default now(),
  constraint area_submission_criterion_scores_pkey primary key (score_id),
  constraint uq_area_submission_criterion_scores_submission_criterion unique (submission_id, criterion_key),
  constraint area_submission_criterion_scores_submission_fkey foreign key (submission_id) references public.area_submissions (submission_id) on delete cascade,
  constraint area_submission_criterion_scores_application_fkey foreign key (application_id) references public.applications (application_id) on delete cascade,
  constraint area_submission_criterion_scores_area_fkey foreign key (area_id) references public.areas (area_id),
  constraint area_submission_criterion_scores_participant_fkey foreign key (reviewed_by) references public.users (user_id)
);

create index if not exists idx_area_submission_criterion_scores_submission_id on public.area_submission_criterion_scores using btree (submission_id);

create index if not exists idx_area_submission_criterion_scores_application_id on public.area_submission_criterion_scores using btree (application_id);

create index if not exists idx_area_submission_criterion_scores_area_id on public.area_submission_criterion_scores using btree (area_id);

create index if not exists idx_area_submission_criterion_scores_part_id on public.area_submission_criterion_scores using btree (part_id);