-- Archive table and RPC for faculty users
-- Paste this into the Supabase SQL editor if you do not want to run it as a migration.

create table if not exists public.archived_faculty_users (
  archive_id bigint generated by default as identity not null,
  source_user_id integer not null,
  name_last character varying(50) not null,
  name_first character varying(50) not null,
  name_middle character varying(50) null,
  domain_email character varying(100) not null,
  password_hash character varying(255) not null,
  role text not null,
  department_id bigint null,
  current_rank character varying(50) null,
  current_salary numeric(12, 2) null,
  nature_of_appointment character varying(50) null,
  educational_attainment character varying(100) null,
  eligibility_exams text null,
  teaching_experience_years integer null default 0,
  industry_experience_years integer null default 0,
  applying_for text null,
  date_of_last_promotion date null,
  status text null default 'inactive'::text,
  is_first_login boolean null default true,
  created_at timestamp with time zone null,
  doctorate jsonb null,
  educational_attainment_json jsonb null,
  eligibility_exams_json jsonb null,
  last_promotion_date date null,
  applying_for_json jsonb null,
  archived_at timestamp with time zone not null default now(),
  archived_by uuid null,
  archived_reason text null,
  constraint archived_faculty_users_pkey primary key (archive_id),
  constraint archived_faculty_users_source_user_id_key unique (source_user_id),
  constraint archived_faculty_users_role_check check (
    role = any (array['HR'::text, 'VPAA'::text, 'Faculty'::text])
  )
);

create index if not exists idx_archived_faculty_users_domain_email
  on public.archived_faculty_users using btree (domain_email);

create index if not exists idx_archived_faculty_users_source_user_id
  on public.archived_faculty_users using btree (source_user_id);

create index if not exists idx_archived_faculty_users_archived_at
  on public.archived_faculty_users using btree (archived_at desc);

create or replace function public.archive_faculty_user(p_user_id integer, p_archived_reason text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.users%rowtype;
  v_archived_by uuid := auth.uid();
begin
  select *
    into v_user
    from public.users
   where user_id = p_user_id;

  if not found then
    raise exception 'User % not found', p_user_id;
  end if;

  insert into public.archived_faculty_users (
    source_user_id,
    name_last,
    name_first,
    name_middle,
    domain_email,
    password_hash,
    role,
    department_id,
    current_rank,
    current_salary,
    nature_of_appointment,
    educational_attainment,
    eligibility_exams,
    teaching_experience_years,
    industry_experience_years,
    applying_for,
    date_of_last_promotion,
    status,
    is_first_login,
    created_at,
    doctorate,
    educational_attainment_json,
    eligibility_exams_json,
    last_promotion_date,
    applying_for_json,
    archived_at,
    archived_by,
    archived_reason
  ) values (
    v_user.user_id,
    v_user.name_last,
    v_user.name_first,
    v_user.name_middle,
    v_user.domain_email,
    v_user.password_hash,
    v_user.role,
    v_user.department_id,
    v_user.current_rank,
    v_user.current_salary,
    v_user.nature_of_appointment,
    v_user.educational_attainment,
    v_user.eligibility_exams,
    v_user.teaching_experience_years,
    v_user.industry_experience_years,
    v_user.applying_for,
    v_user.date_of_last_promotion,
    v_user.status,
    v_user.is_first_login,
    v_user.created_at,
    v_user.doctorate,
    v_user.educational_attainment_json,
    v_user.eligibility_exams_json,
    v_user.last_promotion_date,
    v_user.applying_for_json,
    now(),
    v_archived_by,
    p_archived_reason
  )
  on conflict (source_user_id) do update set
    name_last = excluded.name_last,
    name_first = excluded.name_first,
    name_middle = excluded.name_middle,
    domain_email = excluded.domain_email,
    password_hash = excluded.password_hash,
    role = excluded.role,
    department_id = excluded.department_id,
    current_rank = excluded.current_rank,
    current_salary = excluded.current_salary,
    nature_of_appointment = excluded.nature_of_appointment,
    educational_attainment = excluded.educational_attainment,
    eligibility_exams = excluded.eligibility_exams,
    teaching_experience_years = excluded.teaching_experience_years,
    industry_experience_years = excluded.industry_experience_years,
    applying_for = excluded.applying_for,
    date_of_last_promotion = excluded.date_of_last_promotion,
    status = excluded.status,
    is_first_login = excluded.is_first_login,
    created_at = excluded.created_at,
    doctorate = excluded.doctorate,
    educational_attainment_json = excluded.educational_attainment_json,
    eligibility_exams_json = excluded.eligibility_exams_json,
    last_promotion_date = excluded.last_promotion_date,
    applying_for_json = excluded.applying_for_json,
    archived_at = excluded.archived_at,
    archived_by = excluded.archived_by,
    archived_reason = excluded.archived_reason;

  delete from public.users
   where user_id = p_user_id;
end;
$$;

grant execute on function public.archive_faculty_user(integer, text) to authenticated;